### ISSUE TITLE
Starknet.py API has changed a lot

### ISSUE THREAD

**Issue by FelixGibson** [starknet-edu/starknet-accounts#2]
Hello, everyone, it seems that the API of Starknet.py has changed a lot. Please refer to https://starknetpy.readthedocs.io/en/latest/migration_guide.html  .

Maybe I can help to fix this issue. I'm currently working on it. A couple of days later, I'll pull the request. Am I welcome?

**Comment by 0xLucqs** [comment]
yes you are ! any news on it ? @FelixGibson

**Comment by drspacemn** [comment]
Closing after merged PR, thanks again.
